redir-port: 7890
tproxy-port: 9898
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
tun:
  enable: false
proxies:
proxy-groups:
  - name: "수업"
    type: select
    use:
      - "your"
  - name: "ads-all"
    type: select
    proxies:
      - DIRECT
      - REJECT
proxy-providers:
  your:
    type: file
    path: ./confs/clash.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
rules:
  - GEOSITE,category-ads-all,ads-all
  - MATCH,수업

#  nameserver:
#    - https://ipv6a.cloudflare-dns.com/dns-query
#    - https://dns.cloudflare.com/dns-query
#    - tls://1dot1dot1dot1.cloudflare-dns.com