proxies:
proxy-groups:
- {name: "LYCORIS", type: select, use: [ONLINE, CLASH]}
proxy-providers:
  CLASH:
    type: file
    path: ./confs/clash.yaml
    url: ""
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 1200
  ONLINE:
    type: http
    path: ./confs/online.yaml
    url: "https://raw.githubusercontent.com/stealth-sr/proxy/vpn/guweh.yaml"
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 1200
rules:
- AND,((DST-PORT,5228-5230),(NETWORK,TCP),(DOMAIN-KEYWORD,google)),DIRECT
- IP-CIDR,127.0.0.1/8,DIRECT,no-resolve
- IP-CIDR,198.18.0.1/16,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR6,::1/128,DIRECT,no-resolve
- IP-CIDR6,fc00::/7,DIRECT,no-resolve
- IP-CIDR6,fe80::/10,DIRECT,no-resolve
- IP-CIDR6,fd00::/8,DIRECT,no-resolve
- MATCH,LYCORIS