tproxy-port: 7890
redir-port: 7891
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
# BAGIAN ATAS, JANGAN DI EDIT > INFO CEK GRUP GATCHA

proxies:
  - name: "[trojan] grpc"
    type: trojan
    server: trojan-ovh-sg01.globalssh.xyz
    port: 443
    password: cfm124
    udp: true
    tls: true
    sni: bug.com
    skip-cert-verify: true
    network: grpc
    grpc-opts:
     grpc-service-name: trojan-grpc

  - name: "[trojan] gfw"
    server: sg3-trojan.bonds.id
    port: 443
    type: trojan
    password: 775f4b90-9c68-11ec-a7bc-1239d0255272
    skip-cert-verify: true
    sni: shopee.co.id
    udp: true
  - name: "[trojan] go"
    server: 104.18.21.226
    port: 443
    type: trojan
    password: 775f4b90-9c68-11ec-a7bc-1239d0255272
    skip-cert-verify: true
    sni: sg3-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3-trojan.bonds.id
    udp: true

  - name: "[vmess] ws-tls"
    server: sg4.v2-ray.com
    port: 443
    type: vmess
    uuid: 854fc069-23bc-4dd9-9c14-9f3bc50a3b76
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: shopee.co.id
    network: ws
    ws-opts:
      path: /fastssh/cfm123/622330f16f956/
      headers:
        Host: shopee.co.id
    udp: true

  - name: "[vmess] ntls"
    server: 104.18.21.226
    port: 80
    type: vmess
    uuid: 854fc069-23bc-4dd9-9c14-9f3bc50a3b76
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg4.v2-ray.com
    network: ws
    ws-opts:
      path: /fastssh/cfm123/622330f16f956/
      headers:
        Host: sg4.v2-ray.com
    udp: true

  - name: "[vmess] grpc"
    server: sg1-grpc.serverssh.net
    port: 443
    type: vmess
    uuid: 148d81a6-614a-4fe8-886e-fff223791577
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg1-grpc.serverssh.net
    network: grpc
    grpc-opts:
      grpc-mode: gun
      grpc-service-name: grpc
    udp: true

  - name: "[vless] grpc"
    server: vless-ovh-sg01.globalssh.xyz
    port: 443
    type: vless
    uuid: cbe21d84-c473-49d7-9a19-34276b8f162c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bug.com
    network: grpc
    grpc-opts:
      grpc-mode: gun
      grpc-service-name: grpc
    udp: true

  - name: "[vless] tcp"
    server: vless-ovh-sg01.globalssh.xyz
    port: 443
    type: vless
    uuid: cbe21d84-c473-49d7-9a19-34276b8f162c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bug.com
    udp: true

  - name: "[vless] ws-tls"
    server: id-2.vless.co
    port: 443
    type: vless
    uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bug.vom
    network: ws
    ws-opts:
      path: /fastssh/baku/6223369b05d85/
      headers:
        Host: bug.vom
    udp: true

  - name: "[vless] ntls"
    server: bug.com
    port: 80
    type: vless
    uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id-2.vless.co
    network: ws
    ws-opts:
      path: /fastssh/baku/6223369b05d85/
      headers:
        Host: id-2.vless.co
    udp: true

proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - "[trojan] grpc"
      - "[trojan] gfw"
      - "[trojan] go"
      - "[vmess] ws-tls"
      - "[vmess] ntls"
      - "[vmess] grpc"
      - "[vless] grpc"
      - "[vless] tcp"
      - "[vless] ws-tls"
      - "[vless] ntls"
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
