proxies:
  - name: trojan SSL
    server: sgovh-trojan.bonds.id
    port: 443
    type: trojan
    password: f9e3cff0-ae52-11ec-ab01-1239d0255272
    skip-cert-verify: true
    sni: "shopee.co.id"
    udp: true

  - name: trojan Go
    server: tamarin.mjee.me
    port: 443
    type: trojan
    password: f9e3cff0-ae52-11ec-ab01-1239d0255272
    skip-cert-verify: true
    sni: sgovh-trojan.bonds.id
    udp: true
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sgovh-trojan.bonds.id
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - trojan SSL
      - trojan Go
      - balance
      - best-ping
  - name: balance
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - trojan SSL
      - trojan Go
  - name: best-ping
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - trojan SSL
      - trojan Go
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY