proxies:
proxy-groups:
- {name: "CLASH", type: select, use: [TOUR]}
- {name: "ADS-ALL", type: select, proxies: [REJECT, DIRECT, CLASH]}
proxy-providers:
  TOUR:
    type: file
    path: ./confs/clash.yaml
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 600
rules:
- AND,((DST-PORT,5228-5230),(NETWORK,TCP)),DIRECT
- IP-CIDR,127.0.0.1/8,DIRECT,no-resolve
- IP-CIDR,198.18.0.1/16,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- GEOSITE,CATEGORY-ADS-ALL,ADS-ALL
- MATCH,CLASH